### ISSUE TITLE
Crash on libdeflate gzip files

### ISSUE THREAD

**Issue by M-Gonzalo** [fhanau/Efficient-Compression-Tool#111]
I'm getting crashes for all files created with libdeflate-gzip.

```sh
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
zsh: IOT instruction (core dumped)  ect -9 -gzip --disable-png --disable-jpg --mt-deflate=8 
```

Happens with all levels of libdeflate I try.
I'm using 0.9.3, on Linux x86-64

**Comment by fhanau** [comment]
This was an issue introduced in version 0.9.3 when the gzip code was overhauled and filename support was added, causing crashes for gzip files without file names in the process.
It is fixed in the latest Mac/Windows binaries and the latest source, so please use the latest source version. The 0.9.3 release page mentions this issue, I'm sorry if this was unclear.
