### ISSUE TITLE
compression > 10000?

### ISSUE THREAD

**Issue by eyaler** [fhanau/Efficient-Compression-Tool#116]
I've seen in manual.docx options for compression level > 10000. the doc refers to performance.html but i could not find it. is it available? could you give some examples/recommendations/insights/benchmarks for these modes?

**Comment by krishty** [comment]
It’s really just that. E. g. for maximal PNG compression I call `ect_x64 -30060 --allfilters-b --pal_sort=120 --strip foo.png`, where `30060` means “three blocksplitting passes with 60 iterations”.

I had a few benchmarks regarding block splitting passes and iterations [here](https://encode.su/threads/2274-ECT-an-file-optimizer-with-fast-zopfli-like-deflate-compression?p=61339&viewfull=1#post61339), but modern browsers most likely won’t display the graphics because my site is not HTTPS-encrypted. You’ll have to use _“view source”_ if you’re interested.

Note that I don’t use more than 60 iterations because [that would trigger the extremely slow Ultra2 mode](https://encode.su/threads/2274-ECT-an-file-optimizer-with-fast-zopfli-like-deflate-compression?p=62825&viewfull=1#post62825).

**Comment by fhanau** [comment]
ECT has little documentation on higher compression levels. This is in part intentional as for most use cases level 7 is more than sufficient and using more advanced settings results in wasting CPU time for minuscule compression gains.

If you do want to use higher levels krishty's answer explains the behavior quite well. ultra2 is still very slow and not recommended most of the time, but is several times faster for most cases based on some recent changes.
