### ISSUE TITLE
Can't back up the output file

### ISSUE THREAD

**Issue by salehawal** [fhanau/Efficient-Compression-Tool#61]
Can't back up the output file .. i see this message appears sometimes, what dose it mean?

**Comment by fhanau** [comment]
Due to the relatively primitive architecture of some PNG code, the input file needs to be backed up. If the files infilename.png.bak or infilename.png.bak2 already exist this is not possible and the file will not be processed. This is relatively easy to fix though which I will consider doing soon, so thanks for mentioning this.

**Comment by salehawal** [comment]
is there a way to contact you?

**Comment by fhanau** [comment]
Yes, you can contact me via email, the address is on my profile.
