### ISSUE TITLE
Are JPEGs supposed to be interlaced by default?

### ISSUE THREAD

**Issue by dreamlayers** [fhanau/Efficient-Compression-Tool#78]
JPEGs compress better when interlaced. A progressive (non-interlaced) JPEG can be losslessly converted to interlaced via https://github.com/tjko/jpegoptim. I can get savings of about 9% on camera JPEGs compared to progressive JPEGs.

The existence of `-progressive      Use progressive encoding for JPEGs` in the help output makes me think that ECT should be making JPEGs interlaced by default. There's no option for making them interlaced.

**Comment by fhanau** [comment]
progressive encoding and interlacing are the same thing. Using the progressive flag will always yield the smallest file size since it chooses non-progressive encoding in the rare cases where doing so yields a smaller file (using compression level 1 has some heuristics where this may not apply). It is not enabled by default since it increases decoding time.

**Comment by tssajo** [comment]
@dreamlayers As far as I know, progressive **is** interlaced.

**Comment by dreamlayers** [comment]
Sorry, I was confused by the terminology. In JPEG terminology, progressive does indeed mean interlaced. Non-interlaced is baseline JPEG. But elsewhere, progressive means non-interlaced, like with 1080p vs 1080i or as described at https://en.wikipedia.org/wiki/Interlacing_(bitmaps).
