### ISSUE TITLE
Update LodePNG to version 20200306

### ISSUE THREAD

**Issue by necros2k7** [fhanau/Efficient-Compression-Tool#83]
subj

**Comment by fhanau** [comment]
ECT's lodepng has been heavily modified to remove unused code, improve performance and add features that improve compression. Lodepng had quite a few changes since ECT's version diverged, including bug fixes and a few performance improvements. However, these largely concern code that is not used by ECT. I think there would be only a small improvement to stability and no or little impact on performance while it would take a lot of work to integrate these changes.
