### ISSUE TITLE
Release with -recurse option enabled

### ISSUE THREAD

**Issue by JosePineiro** [fhanau/Efficient-Compression-Tool#84]
I like one excecutable with -recurse option enabled
Because is disabled?

**Comment by fhanau** [comment]
Building with the -recurse option requires additional libraries. The last time I tried building it that way on Windows, I could not figure out how to link it properly. ECT is primarily written for a Unix environment and I am less familiar with getting everything to work properly on Windows. While I will not provide binaries with directory support at this time, your shell should make it easy to use ECT on all files in a directory.

**Comment by Mongogamer** [comment]
I compiled a version with directory support but it is roughly 5x larger in filesize than the current release here on github. Setting the compilation and linking up properly was also somewhat of a pain but it is much better now than a few months earlier this year. I assume the difference is due to previously having used a self compiled version of libboost instead of the MSYS2 version. Just in case I would recommend compiling your own version in case you can figure out a way to keep the filesize smaller.


[ect.zip](https://github.com/fhanau/Efficient-Compression-Tool/files/4730249/ect.zip)

**Comment by JosePineiro** [comment]
Thanks

Work ok in my side. The new ect filesize is not problem.
